# Global configuration for ARC DSL, search, model, training, and eval
# All modules must import values from app.config or app.utils.tokens; no hardcoded literals in code.

dsl:
  max_depth: 4
  max_arity: 2
  num_colors: 10            # ARC color palette size (0..9)
  max_grid_size: 30         # safety clamp for crop/pad
  enum_numeric_values: [0,1,2,3,4,5,6,7,8,9]
  rotations: [0,1,2,3]      # k for np.rot90
  reflections: [0,1,2,3,4]  # 0:none, 1:vertical, 2:horizontal, 3:diag_main, 4:diag_anti
  enable_ops: [MAP_COLOR, FILTER_EQ, ROTATE, REFLECT, CROP, PAD, COMPOSE]

# Token ID base offsets. We keep them here so nothing is hardcoded in code.
tokens:
  START: 1
  END: 2
  COMPOSE: 3
  MAP_COLOR: 10
  FILTER_EQ: 11
  ROTATE: 12
  REFLECT: 13
  CROP: 14
  PAD: 15
  BASE_NUM: 100            # numbers (coordinates/amounts): BASE_NUM + i
  BASE_COLOR: 200          # color tokens: BASE_COLOR + color_id
  BASE_ROT: 300            # rotation k tokens
  BASE_REFLECT: 320        # reflect type tokens

search:
  beam_width: 128
  max_nodes: 20000
  max_expansions_per_node: 128
  cache_results: true
  bad_score: -1e9
  # Typed incremental search weights
  typed_w_logprob: 1.0
  typed_w_heur: 1.0
  # Pair subset selection for heuristic execution scoring
  pair_subset_enable: true
  pair_subset_k: 2
  pair_subset_strategy: entropy_size
  # Optional policy-specific search limits (fallback to beam_width/max_nodes if unset)
  policy_beam_width: 128
  policy_max_nodes: 20000

training:
  pseudo_max_depth: 3
  task_limit: 200
  batch_size: 512
  epochs: 10
  lr: 0.0005
  weight_decay: 0.0
  grad_clip: 1.0
  entropy_coef: 0.0
  kl_coef: 0.0
  seed: 42

model:
  d_model: 256
  nhead: 8
  nlayers: 4
  dropout: 0.1
  max_tokens: 256
  # CNN backbone
  use_cnn_backbone: true
  cnn_channels: [64, 128]
  cnn_blocks_per_stage: [1, 1]
  cnn_kernel_size: 3
  cnn_norm: batch     # batch|layer|none
  cnn_pool: avg       # avg|max
  # Input encoding
  input_onehot: true
  # Object-centric branch
  use_object_branch: true
  components_connectivity: 4
  components_background_color: 0
  obj_max_components: 64
  obj_hidden: 128
  obj_heads: 4
  obj_layers: 2
  obj_pool: attn      # attn|mean
  # Fusion
  context_fusion: concat_proj

inference:
  time_budget_s: 30
  beam_width: 128
  max_nodes: 20000
  use_policy: true
  num_workers: 8
  time_budget_disable_threshold: 0.0
  parallel_min_workers: 2
  parallel_min_tasks: 2
  progress_interval: 1
